"""
manifest_check.py — Compare MANIFEST.txt hashes against current file hashes.

Reads the tracked file list from MANIFEST.txt, computes fresh hashes for
each file found on disk, and prints a side-by-side comparison table.
Writes the result to MANIFEST_current.txt in the same directory.

Usage:
    manifest-check <project_root>
    manifest-check .                      # current directory
    manifest-check C:\\path\\to\\project

Output:
    Console table + MANIFEST_current.txt
"""

import argparse
import os
import sys

from packtools._hashing import sha16, bundle_hash


def load_manifest(manifest_path: str) -> tuple[str | None, dict[str, str]]:
    """
    Parse MANIFEST.txt → (bundle_hash, {local_path: expected_sha16}).

    Skips blank lines and comment lines (starting with #).
    """
    expected_bundle = None
    files: dict[str, str] = {}
    with open(manifest_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n\r")
            if not line or line.startswith("#"):
                continue
            if line.startswith("bundle:"):
                expected_bundle = line.split("\t", 1)[1].strip()
                continue
            parts = line.split("\t", 1)
            if len(parts) == 2:
                files[parts[1].strip()] = parts[0].strip()
    return expected_bundle, files


def check(root: str) -> None:
    """Run the manifest check for project_root and write MANIFEST_current.txt."""
    manifest_path = os.path.join(root, "MANIFEST.txt")
    if not os.path.exists(manifest_path):
        print("Error: MANIFEST.txt not found in %s" % root)
        sys.exit(1)

    expected_bundle, tracked = load_manifest(manifest_path)

    rows: list[tuple[str, str, str, str]] = []
    current_hashes: dict[str, str] = {}
    for local_path, expected_sha in tracked.items():
        full_path = os.path.join(root, local_path.replace("/", os.sep))
        if os.path.exists(full_path):
            with open(full_path, "rb") as f:
                current_sha = sha16(f.read())
        else:
            current_sha = "MISSING"
        current_hashes[local_path] = current_sha
        status = "OK" if current_sha == expected_sha else (
            "MISSING" if current_sha == "MISSING" else "CHANGED"
        )
        rows.append((local_path, expected_sha, current_sha, status))

    current_bundle = bundle_hash(
        {p: s for p, s in current_hashes.items() if s != "MISSING"}
    )
    bundle_status = "OK" if current_bundle == expected_bundle else "CHANGED"

    # Format table
    W_path = max(max(len(r[0]) for r in rows), 4)
    header = "%-*s  %-16s  %-16s  %s" % (W_path, "File", "MANIFEST", "Current", "Status")
    sep    = "-" * len(header)

    lines = [header, sep]
    for path, expected, current, status in rows:
        lines.append("%-*s  %-16s  %-16s  %s" % (W_path, path, expected, current, status))
    lines.append(sep)
    lines.append("%-*s  %-16s  %-16s  %s" % (
        W_path, "BUNDLE", expected_bundle or "(none)", current_bundle, bundle_status,
    ))

    table = "\n".join(lines) + "\n"
    print()
    print(table)

    out_path = os.path.join(root, "MANIFEST_current.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Generated by manifest-check\n")
        f.write("# Source: %s\n" % manifest_path)
        f.write("#\n")
        f.write(table)

    n_ok      = sum(1 for r in rows if r[3] == "OK")
    n_changed = sum(1 for r in rows if r[3] == "CHANGED")
    n_missing = sum(1 for r in rows if r[3] == "MISSING")
    print("Wrote: %s" % out_path)
    print("Files: %d OK  %d changed  %d missing  |  Bundle: %s" % (
        n_ok, n_changed, n_missing, bundle_status,
    ))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compare MANIFEST.txt hashes against current file hashes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("project_root", nargs="?", default=".",
        help="Root directory containing MANIFEST.txt (default: current directory)")
    args = parser.parse_args()

    check(os.path.abspath(args.project_root))


if __name__ == "__main__":
    main()
