"""
manifest_check.py — Compare MANIFEST.txt hashes against current file hashes.

Reads the tracked file list from MANIFEST.txt, computes fresh hashes for each
file found on disk, and prints a side-by-side comparison table.  Writes the
result to MANIFEST_current.txt in the same directory.

Usage:
    python manifest_check.py <project_root>
    python manifest_check.py .                  # current directory
    python manifest_check.py C:\\path\\to\\project
"""

import hashlib
import os
import sys


def sha16(data: bytes) -> str:
    """SHA-256 of CRLF-normalised bytes, first 16 hex chars."""
    n = data.replace(b"\r\n", b"\n").replace(b"\n", b"\r\n")
    return hashlib.sha256(n).hexdigest()[:16]


def load_manifest(manifest_path: str) -> tuple[str | None, dict[str, str]]:
    """Parse MANIFEST.txt → (bundle_hash, {local_path: expected_sha16})."""
    bundle = None
    files: dict[str, str] = {}
    with open(manifest_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n\r")
            if not line or line.startswith("#"):
                continue
            if line.startswith("bundle:"):
                bundle = line.split("\t", 1)[1].strip()
                continue
            parts = line.split("\t", 1)
            if len(parts) == 2:
                files[parts[1].strip()] = parts[0].strip()
    return bundle, files


def bundle_hash(file_hashes: dict[str, str]) -> str:
    """Hash-of-hashes: sort by path, concatenate sha16s, SHA-256, 24 chars."""
    concatenated = "".join(sha for _, sha in sorted(file_hashes.items()))
    return hashlib.sha256(concatenated.encode()).hexdigest()[:24]


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python manifest_check.py <project_root>")
        sys.exit(1)

    root = os.path.abspath(sys.argv[1])
    manifest_path = os.path.join(root, "MANIFEST.txt")

    if not os.path.exists(manifest_path):
        print("Error: MANIFEST.txt not found in %s" % root)
        sys.exit(1)

    expected_bundle, tracked = load_manifest(manifest_path)

    # Compute current hashes
    rows = []
    current_hashes: dict[str, str] = {}
    for local_path, expected_sha in tracked.items():
        full_path = os.path.join(root, local_path.replace("/", os.sep))
        if os.path.exists(full_path):
            with open(full_path, "rb") as f:
                data = f.read()
            current_sha = sha16(data)
        else:
            current_sha = "MISSING"
        current_hashes[local_path] = current_sha
        match = "OK" if current_sha == expected_sha else (
            "MISSING" if current_sha == "MISSING" else "CHANGED"
        )
        rows.append((local_path, expected_sha, current_sha, match))

    # Bundle hashes
    current_bundle = bundle_hash(
        {p: s for p, s in current_hashes.items() if s != "MISSING"}
    )
    bundle_match = "OK" if current_bundle == expected_bundle else "CHANGED"

    # Format table
    W_path    = max(len(r[0]) for r in rows)
    W_path    = max(W_path, 4)
    header    = "%-*s  %-16s  %-16s  %s" % (W_path, "File", "MANIFEST", "Current", "Status")
    separator = "-" * len(header)

    lines = [header, separator]
    for path, expected, current, status in rows:
        lines.append("%-*s  %-16s  %-16s  %s" % (W_path, path, expected, current, status))
    lines.append(separator)
    lines.append("%-*s  %-16s  %-16s  %s" % (
        W_path, "BUNDLE", expected_bundle or "(none)", current_bundle, bundle_match
    ))

    output = "\n".join(lines) + "\n"

    # Print to console
    print()
    print(output)

    # Write MANIFEST_current.txt
    out_path = os.path.join(root, "MANIFEST_current.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Generated by manifest_check.py\n")
        f.write("# Source: %s\n" % manifest_path)
        f.write("# \n")
        f.write(output)

    # Summary
    n_ok      = sum(1 for r in rows if r[3] == "OK")
    n_changed = sum(1 for r in rows if r[3] == "CHANGED")
    n_missing = sum(1 for r in rows if r[3] == "MISSING")
    print("Wrote: %s" % out_path)
    print("Files: %d OK  %d changed  %d missing  |  Bundle: %s" % (
        n_ok, n_changed, n_missing, bundle_match
    ))


if __name__ == "__main__":
    main()
